name: "Analyze"

on:
  push:
  pull_request:
  schedule:
    - cron: "0 19 * * 0"
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Job triggered by ${{ github.event_name }} event."

      - name: Checkout
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      - name: APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        id: cache-deps
        with:
          packages: dia doxygen doxygen-doc doxygen-gui doxygen-latex graphviz mscgen

      # Initializes the CodeQL tools for scanning.
      - name: Initialize
        uses: github/codeql-action/init@v1

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Analyze
        uses: github/codeql-action/analyze@v1
