name: Deploy Website

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Job triggered by ${{github.event_name}} event."

      - name: Checkout
        uses: actions/checkout@v2

      - name: APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        id: cache-deps
        with:
          packages: dia doxygen doxygen-doc doxygen-gui doxygen-latex graphviz mscgen

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ${{github.workspace}}/build/website
