name: Integrate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  integrate:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Job triggered by ${{ github.event_name }} event."

      - name: Checkout
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - name: Checkout (pull request)
        run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        id: cache-deps
        with:
          packages: dia doxygen doxygen-doc doxygen-gui doxygen-latex graphviz mscgen

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
