name: Integrate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  integrate:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Job triggered by ${{ github.event_name }} event."

      - name: Checkout
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - name: Checkout (pull request)
        run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Cache Dependencies
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: "~/cache-deps"
          key: cache-deps

      - name: Install Dependencies
        run: ${{github.workspace}}/.github/workflows/deps_install.sh "~/cache-deps"

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
