name: Release

on:
  push:
    branches: [master]
    tags:
      - "*"
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Job triggered by ${{github.event_name}} event."

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: "~/cache-deps"
          key: cache-deps

      - name: Install Dependencies
        run: ${{github.workspace}}/.github/workflows/deps_install.sh "~/cache-deps"

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ${{github.workspace}}/build/website

# TODO Enable once library builds are file path qualified.
#       - name: Create Release Package
#         uses: ncipollo/release-action@v1
#         with:
#           bodyFile: "README.md"
#           token: ${{secrets.GITHUB_TOKEN}}
