name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag"
        required: true
      notes:
        description: "Release notes"
        required: true

env:
  BUILD_TYPE: Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Job triggered by ${{github.event_name}} event."

      - name: Checkout
        uses: actions/checkout@v2

      - name: APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        id: cache-deps
        with:
          packages: dia doxygen doxygen-doc doxygen-gui doxygen-latex graphviz mscgen

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DBUILD_TESTS=ON \
          -DBUILD_WEBSITE=ON

      - name: Build
        run: cd ${{github.workspace}}/build; make

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: cd ${{github.workspace}}/build; ctest -C ${{env.BUILD_TYPE}}

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ${{github.workspace}}/build/website

      - name: Create Release Package Artifacts
        run: |
          ${{github.workspace}}/.github/workflows/create_release_pkg_artifacts.sh \
            ${{github.workspace}} \
            ${{github.event.inputs.tag}} \
            "${{github.event.inputs.notes}}"

      - name: Create Tag
        run: git tag ${{github.event.inputs.tag}}; git push origin --tags

      - name: Create Release Package
        uses: ncipollo/release-action@v1
        with:
          bodyFile: ${{github.workspace}}/release/notes.md
          artifacts: |
            ${{github.workspace}}/release/fluentcpp-${{github.event.inputs.tag}}.tar.gz \
            ${{github.workspace}}/release/fluentcpp-${{github.event.inputs.tag}}.zip
          tag: ${{github.event.inputs.tag}}
          token: ${{secrets.GITHUB_TOKEN}}
