name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag"
        required: true
      notes:
        description: "Release notes"
        required: false

env:
  BUILD_TYPE: Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Job triggered by ${{github.event_name}} event."

      - name: Checkout
        uses: actions/checkout@v2

      - name: APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        id: cache-deps
        with:
          packages: dia doxygen doxygen-doc doxygen-gui doxygen-latex graphviz mscgen

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -RUN_TESTS=true \
            -DBUILD_WEBSITE=true

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ${{github.workspace}}/build/website

      - name: Create Release Package Artifacts
        run: |
          ${{github.workspace}}/.github/workflows/create_release_pkg_artifacts.sh \
            ${{github.workspace}} \
            ${{github.event.inputs.tag}} \
            "${{github.event.inputs.notes}}"

      - name: Create Tag
        run: git tag ${{github.event.inputs.tag}}; git push origin --tags

      - name: Create Release Package
        uses: ncipollo/release-action@v1
        with:
          bodyFile: ${{github.workspace}}/release/notes.md
          artifacts: fluentcpp-${{github.event.inputs.tag}}.tar.gz
          tag: ${{github.event.inputs.tag}}
          token: ${{secrets.GITHUB_TOKEN}}
